easy_wordlist = [
    "egg",
    "toy",
    "water",
    "day",
    "shower",
    "tiger",
    "home",
    "coat",
    "garden",
    "rise",
    "throw",
    "crown",
    "baby",
    "garden",
    "office",
    "beach",
    "phone",
    "computer",
    "flower",
    "bank",
    "train",
    "brush",
    "pole",
    "game",
    "apple",
    "ball",
    "banana",
    "bear",
    "bed",
    "bee",
    "bird",
    "blue",
    "boat",
    "book",
    "bread",
    "broom",
    "cake",
    "car",
    "cat",
    "chair",
    "cheese",
    "cloud",
    "coat",
    "corn",
    "cow",
    "crab",
    "cup",
    "deer",
    "desk",
    "dog",
    "door",
    "duck",
    "egg",
    "farm",
    "fish",
    "flower",
    "food",
    "fox",
    "frog",
    "game",
    "gift",
    "girl",
    "goat",
    "grape",
    "grass",
    "green",
    "hat",
    "hill",
    "home",
    "horse",
    "house",
    "juice",
    "kite",
    "lake",
    "leaf",
    "lion",
    "milk",
    "moon",
    "mouse",
    "mouth",
    "nest",
    "night",
    "orange",
    "owl",
    "park",
    "pear",
    "pen",
    "pig",
    "pizza",
    "plane",
    "plant",
    "plate",
    "pond",
    "rain",
    "red",
    "rice",
    "ring",
    "river",
    "road",
    "rock",
    "room",
    "rope",
    "shoe",
    "shop",
    "sky",
    "snake",
    "snow",
    "sock",
    "spoon",
    "star",
    "sun",
    "table",
    "tail",
    "tiger",
    "train",
    "tree",
    "truck",
    "water",
    "whale",
    "white",
    "wind",
    "wolf",
    "yellow",
    "zebra",
]

medium_wordlist = [
    "soup",
    "tree",
    "orange",
    "mango",
    "coding",
    "program",
    "uncle",
    "aunty",
    "inspiration",
    "traffic",
    "hallway",
    "secure",
    "sow",
    "orange",
    "general",
    "brick",
    "absence",
    "haircut",
    "bottle",
    "host",
    "adventure",
    "airport",
    "animal",
    "answer",
    "artist",
    "autumn",
    "backpack",
    "bakery",
    "balloon",
    "baseball",
    "basket",
    "beach",
    "beaver",
    "bicycle",
    "blanket",
    "bottle",
    "bridge",
    "button",
    "camera",
    "candle",
    "castle",
    "cereal",
    "cherry",
    "circle",
    "circus",
    "closet",
    "coffee",
    "cookie",
    "cousin",
    "crayon",
    "dancer",
    "dinner",
    "dolphin",
    "dragon",
    "drawer",
    "driver",
    "eagle",
    "engine",
    "family",
    "farmer",
    "feather",
    "forest",
    "friend",
    "garden",
    "guitar",
    "hammer",
    "helmet",
    "holiday",
    "island",
    "jacket",
    "jungle",
    "kitten",
    "ladder",
    "library",
    "market",
    "mirror",
    "monkey",
    "morning",
    "mountain",
    "museum",
    "napkin",
    "nature",
    "notebook",
    "ocean",
    "painter",
    "pancake",
    "parrot",
    "pencil",
    "pepper",
    "picnic",
    "pirate",
    "planet",
    "pocket",
    "puppy",
    "rabbit",
    "rainbow",
    "rocket",
    "school",
    "shadow",
    "shovel",
    "singer",
    "soccer",
    "spider",
    "spring",
    "square",
    "stairs",
    "summer",
    "sunset",
    "teacher",
    "ticket",
    "turtle",
    "vacation",
    "valley",
    "village",
    "window",
    "winter",
    "wizard",
    "wonder",
    "yellow",
    "zombie",
]
hard_wordlist = [
    "uncanny",
    "ironic",
    "literally",
    "procrastination",
    "endure",
    "advocate",
    "baffle",
    "barren",
    "devote",
    "fathom",
    "gibberish",
    "hostile",
    "insane",
    "kudos",
    "lunatic",
    "mundane",
    "obscure",
    "quantum",
    "pseudonym",
    "quench",
    "solace",
    "tedious",
    "accordion",
    "astronaut",
    "avalanche",
    "beautiful",
    "binoculars",
    "blueberry",
    "butterfly",
    "calendar",
    "carnival",
    "carpenter",
    "caterpillar",
    "celebrate",
    "chocolate",
    "compass",
    "computer",
    "constellation",
    "crocodile",
    "curiosity",
    "dangerous",
    "delicious",
    "diamond",
    "dinosaur",
    "discovery",
    "earthquake",
    "elephant",
    "enormous",
    "exercise",
    "explorer",
    "firefighter",
    "flashlight",
    "fountain",
    "friendship",
    "galaxy",
    "giraffe",
    "harmonica",
    "helicopter",
    "hibernate",
    "hospital",
    "important",
    "instrument",
    "jellyfish",
    "kangaroo",
    "knowledge",
    "lighthouse",
    "lightning",
    "magician",
    "marshmallow",
    "microscope",
    "mysterious",
    "neighborhood",
    "octopus",
    "orchestra",
    "parachute",
    "penguin",
    "photograph",
    "pineapple",
    "playground",
    "porcupine",
    "president",
    "question",
    "refrigerator",
    "restaurant",
    "rhinoceros",
    "sandwich",
    "satellite",
    "scarecrow",
    "scientist",
    "scorpion",
    "seashell",
    "skateboard",
    "snowflake",
    "spaceship",
    "squirrel",
    "strawberry",
    "submarine",
    "sunflower",
    "surprise",
    "telescope",
    "temperature",
    "thunderstorm",
    "toothbrush",
    "tournament",
    "treasure",
    "triangle",
    "umbrella",
    "universe",
    "vegetable",
    "volcano",
    "waterfall",
    "weather",
    "whisper",
    "wilderness",
    "xylophone",
    "yesterday",
    "zeppelin",
]
insane_wordlist = [
    "archaeology",
    "bougainvillea",
    "chrysanthemum",
    "circumference",
    "conscientious",
    "crystallization",
    "electromagnetism",
    "entrepreneur",
    "extraordinary",
    "fluorescent",
    "hippopotamus",
    "incomprehensible",
    "indistinguishable",
    "jurisdiction",
    "kaleidoscope",
    "metamorphosis",
    "miscellaneous",
    "onomatopoeia",
    "photosynthesis",
    "pneumonia",
    "quintessential",
    "reconciliation",
    "rhinoceros",
    "spectacular",
    "thermodynamics",
    "uncharacteristic",
    "ventriloquist",
    "weatherproof",
    "xylophonist",
    "zoological",
]
wrong_answer_replies = [
    "WRONG!!!! Try Again",
    "NO WAY.... not even close!!",
    "nope...........",
    "ooof.. no, none of THAT letter up here!!",
    "is that your final answer??? too late, wrong!",
    "try again! maybe you should phone a friend?!",
    "email from VannaWhite:📨 R S T L N E",
    "OH SO CLOSE! 🧟",
    "Nope 😅",
    "Wrong turn 🚧",
    "Not today, letter 😎",
    "That guess flopped 💀",
    "Swing and a miss ⚾",
    "Bruh... no 😂",
    "Nice try, detective 🕵️",
    "That letter ghosted you 👻",
    "Certified miss ✅",
    "Oof, not quite 😬",
    "Plot twist: wrong 😱",
    "Mission failed 🚨",
    "That guess was sus 👀",
    "Big nope energy 🚫",
    "Yeet that guess 🗑️",
    "Almost cooked 🍳",
    "Wrong letter unlocked 🔓",
    "Not in this universe 🌌",
    "Close... but no banana 🍌",
    "Guess.exe has crashed 💻",
]
correct_answer_replies = [
    "Correct! 🎉",
    "Nice one! 😎",
    "You got it! ✅",
    "Boom! 💥",
    "Great guess! 🌟",
    "That’s the one! 🔥",
    "Big brain move 🧠",
    "Letter secured 🔒",
    "Perfect pick! 🎯",
    "Winner energy 🏆",
    "Let’s gooo! 🚀",
    "Clean guess ✨",
    "Absolutely nailed it 🔨",
    "Certified correct ✅",
    "That guess cooked 🍳",
    "Unlocked! 🔓",
    "Smart move, detective 🕵️",
    "Correct.exe is running 💻",
    "Easy win 😏",
    "Keep it rolling 🎲",
]
