easy_wordlist = [
    ("APPLE", "Food"),
    ("BANANA", "Food"),
    ("PIZZA", "Food"),
    ("BURGER", "Food"),
    ("COOKIE", "Food"),
    ("DONUT", "Food"),
    ("CHEESE", "Food"),
    ("TACO", "Food"),
    ("CAKE", "Food"),
    ("CANDY", "Food"),
    ("DOG", "Animals"),
    ("CAT", "Animals"),
    ("HORSE", "Animals"),
    ("MOUSE", "Animals"),
    ("TIGER", "Animals"),
    ("LION", "Animals"),
    ("BEAR", "Animals"),
    ("FROG", "Animals"),
    ("DUCK", "Animals"),
    ("SHARK", "Animals"),
    ("HOUSE", "Things Around the House"),
    ("CHAIR", "Things Around the House"),
    ("TABLE", "Things Around the House"),
    ("DOOR", "Things Around the House"),
    ("WINDOW", "Things Around the House"),
    ("COUCH", "Things Around the House"),
    ("BED", "Things Around the House"),
    ("LAMP", "Things Around the House"),
    ("CLOCK", "Things Around the House"),
    ("MIRROR", "Things Around the House"),
    ("PENCIL", "School Supplies"),
    ("PAPER", "School Supplies"),
    ("BOOK", "School Supplies"),
    ("ERASER", "School Supplies"),
    ("CRAYON", "School Supplies"),
    ("MARKER", "School Supplies"),
    ("RULER", "School Supplies"),
    ("SCISSORS", "School Supplies"),
    ("BACKPACK", "School Supplies"),
    ("NOTEBOOK", "School Supplies"),
    ("CAR", "Vehicles"),
    ("TRUCK", "Vehicles"),
    ("BUS", "Vehicles"),
    ("TRAIN", "Vehicles"),
    ("BOAT", "Vehicles"),
    ("BIKE", "Vehicles"),
    ("PLANE", "Vehicles"),
    ("ROCKET", "Vehicles"),
    ("TAXI", "Vehicles"),
    ("SCOOTER", "Vehicles"),
    ("SUN", "Nature"),
    ("MOON", "Nature"),
    ("STAR", "Nature"),
    ("CLOUD", "Nature"),
    ("RAIN", "Nature"),
    ("SNOW", "Nature"),
    ("WIND", "Nature"),
    ("TREE", "Nature"),
    ("FLOWER", "Nature"),
    ("RIVER", "Nature"),
    ("SHIRT", "Clothing"),
    ("PANTS", "Clothing"),
    ("SHOES", "Clothing"),
    ("SOCKS", "Clothing"),
    ("HAT", "Clothing"),
    ("COAT", "Clothing"),
    ("DRESS", "Clothing"),
    ("GLOVE", "Clothing"),
    ("SCARF", "Clothing"),
    ("BELT", "Clothing"),
    ("BATMAN", "Superheroes"),
    ("SUPERMAN", "Superheroes"),
    ("SPIDERMAN", "Superheroes"),
    ("HULK", "Superheroes"),
    ("THOR", "Superheroes"),
    ("FLASH", "Superheroes"),
    ("ROBIN", "Superheroes"),
    ("WONDERWOMAN", "Superheroes"),
    ("IRONMAN", "Superheroes"),
    ("AQUAMAN", "Superheroes"),
    ("PIRATE", "People"),
    ("DOCTOR", "People"),
    ("FARMER", "People"),
    ("PILOT", "People"),
    ("TEACHER", "People"),
    ("CHEF", "People"),
    ("POLICE", "People"),
    ("FIREFIGHTER", "People"),
    ("ARTIST", "People"),
    ("SINGER", "People"),
    ("SOCCER", "Sports"),
    ("BASEBALL", "Sports"),
    ("FOOTBALL", "Sports"),
    ("TENNIS", "Sports"),
    ("HOCKEY", "Sports"),
    ("BASKETBALL", "Sports"),
    ("GOLF", "Sports"),
    ("BOXING", "Sports"),
    ("SKATING", "Sports"),
    ("RACING", "Sports"),
    ("GUITAR", "Music"),
    ("PIANO", "Music"),
    ("DRUMS", "Music"),
    ("VIOLIN", "Music"),
    ("SINGER", "Music"),
]

hard_wordlist = [
    ("AVALANCHE", "Nature"),
    ("THUNDERSTORM", "Nature"),
    ("HURRICANE", "Nature"),
    ("EARTHQUAKE", "Nature"),
    ("VOLCANO", "Nature"),
    ("WATERFALL", "Nature"),
    ("LIGHTNING", "Nature"),
    ("TORNADO", "Nature"),
    ("WILDFIRE", "Nature"),
    ("GLACIER", "Nature"),
    ("CROCODILE", "Animals"),
    ("CHAMELEON", "Animals"),
    ("PORCUPINE", "Animals"),
    ("PLATYPUS", "Animals"),
    ("KANGAROO", "Animals"),
    ("RHINOCEROS", "Animals"),
    ("HIPPOPOTAMUS", "Animals"),
    ("FLAMINGO", "Animals"),
    ("SCORPION", "Animals"),
    ("WOLVERINE", "Animals"),
    ("BUTTERFLY", "Animals"),
    ("DRAGONFLY", "Animals"),
    ("SEAHORSE", "Animals"),
    ("PENGUIN", "Animals"),
    ("CHIMPANZEE", "Animals"),
    ("STRAWBERRY", "Food"),
    ("WATERMELON", "Food"),
    ("PINEAPPLE", "Food"),
    ("BLUEBERRY", "Food"),
    ("RASPBERRY", "Food"),
    ("SPAGHETTI", "Food"),
    ("QUESADILLA", "Food"),
    ("BURRITO", "Food"),
    ("GUACAMOLE", "Food"),
    ("PANCAKES", "Food"),
    ("CHEESECAKE", "Food"),
    ("CUPCAKE", "Food"),
    ("POPCORN", "Food"),
    ("CHOCOLATE", "Food"),
    ("MARSHMALLOW", "Food"),
    ("REFRIGERATOR", "Things Around the House"),
    ("DISHWASHER", "Things Around the House"),
    ("MICROWAVE", "Things Around the House"),
    ("VACUUMCLEANER", "Things Around the House"),
    ("BOOKSHELF", "Things Around the House"),
    ("TELEVISION", "Things Around the House"),
    ("FLASHLIGHT", "Things Around the House"),
    ("THERMOSTAT", "Things Around the House"),
    ("TOOTHBRUSH", "Things Around the House"),
    ("HAIRDRYER", "Things Around the House"),
    ("MOTORCYCLE", "Vehicles"),
    ("HELICOPTER", "Vehicles"),
    ("SUBMARINE", "Vehicles"),
    ("LOCOMOTIVE", "Vehicles"),
    ("AMBULANCE", "Vehicles"),
    ("FIRETRUCK", "Vehicles"),
    ("LIMOUSINE", "Vehicles"),
    ("TRACTOR", "Vehicles"),
    ("SKATEBOARD", "Vehicles"),
    ("SPACESHIP", "Vehicles"),
    ("DINOSAUR", "Prehistoric"),
    ("TYRANNOSAURUS", "Prehistoric"),
    ("TRICERATOPS", "Prehistoric"),
    ("STEGOSAURUS", "Prehistoric"),
    ("VELOCIRAPTOR", "Prehistoric"),
    ("PTERODACTYL", "Prehistoric"),
    ("BRACHIOSAURUS", "Prehistoric"),
    ("PALEONTOLOGIST", "Prehistoric"),
    ("FOSSIL", "Prehistoric"),
    ("EXTINCTION", "Prehistoric"),
    ("TREASURE", "Adventure"),
    ("COMPASS", "Adventure"),
    ("TELESCOPE", "Adventure"),
    ("BINOCULARS", "Adventure"),
    ("BACKPACKING", "Adventure"),
    ("EXPLORATION", "Adventure"),
    ("EXPEDITION", "Adventure"),
    ("PIRATE", "Adventure"),
    ("CASTAWAY", "Adventure"),
    ("SHIPWRECK", "Adventure"),
    ("WEREWOLF", "Fantasy"),
    ("VAMPIRE", "Fantasy"),
    ("UNICORN", "Fantasy"),
    ("MERMAID", "Fantasy"),
    ("DRAGON", "Fantasy"),
    ("WIZARD", "Fantasy"),
    ("SORCERER", "Fantasy"),
    ("FAIRYTALE", "Fantasy"),
    ("SPELLBOOK", "Fantasy"),
    ("ENCHANTMENT", "Fantasy"),
    ("VOLLEYBALL", "Sports"),
    ("GYMNASTICS", "Sports"),
    ("SNOWBOARDING", "Sports"),
    ("SKATEBOARDING", "Sports"),
    ("CHAMPIONSHIP", "Sports"),
    ("TOUCHDOWN", "Sports"),
    ("QUARTERBACK", "Sports"),
    ("BASKETBALL", "Sports"),
    ("SWIMMING", "Sports"),
    ("ARCHERY", "Sports"),
    ("KEYBOARD", "Technology"),
    ("COMPUTER", "Technology"),
    ("SMARTPHONE", "Technology"),
    ("HEADPHONES", "Technology"),
    ("MICROPHONE", "Technology"),
    ("TELESCOPIC", "Technology"),
    ("SATELLITE", "Technology"),
    ("ROBOTICS", "Technology"),
    ("PROGRAMMING", "Technology"),
    ("ALGORITHM", "Technology"),
]

wrong_answer_replies = [
    "WRONG!!!! Try Again",
    "NO WAY.... not even close!!",
    "nope...........",
    "ooof.. no, none of THAT letter up here!!",
    "is that your final answer??? too late, wrong!",
    "try again! maybe you should phone a friend?!",
    "email from VannaWhite:📨 R S T L N E",
    "OH SO CLOSE! 🧟",
    "Nope 😅",
    "Wrong turn 🚧",
    "Not today, letter 😎",
    "That guess flopped 💀",
    "Swing and a miss ⚾",
    "Bruh... no 😂",
    "Nice try, detective 🕵️",
    "That letter ghosted you 👻",
    "Certified miss ✅",
    "Oof, not quite 😬",
    "Plot twist: wrong 😱",
    "Mission failed 🚨",
    "That guess was sus 👀",
    "Big nope energy 🚫",
    "Yeet that guess 🗑️",
    "Almost cooked 🍳",
    "Wrong letter unlocked 🔓",
    "Not in this universe 🌌",
    "Close... but no banana 🍌",
    "Guess.exe has crashed 💻",
]
correct_answer_replies = [
    "Correct! 🎉",
    "Nice one! 😎",
    "You got it! ✅",
    "Boom! 💥",
    "Great guess! 🌟",
    "That’s the one! 🔥",
    "Big brain move 🧠",
    "Letter secured 🔒",
    "Perfect pick! 🎯",
    "Winner energy 🏆",
    "Let’s gooo! 🚀",
    "Clean guess ✨",
    "Absolutely nailed it 🔨",
    "Certified correct ✅",
    "That guess cooked 🍳",
    "Unlocked! 🔓",
    "Smart move, detective 🕵️",
    "Correct.exe is running 💻",
    "Easy win 😏",
    "Keep it rolling 🎲",
]
